platform :ios, '9.0'

target 'TabsKeepersApp' do
pod 'DataAdapterSDK', :path => '../AdapterSDK'
pod 'FDFullscreenPopGesture'
pod 'Masonry'
pod 'YYModel'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'WMPageController', '~> 2.5.2'  #分页控制器
pod 'IQKeyboardManager', '~> 6.2.0' #键盘遮挡
pod 'HXPhotoPicker', '~> 2.2.3' #相册选择
end

pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end

#unable UUID
install! 'cocoapods',
:deterministic_uuids => false
